site_name: TiemGiamGia Docs
site_url: https://docs.tiemgiamgia.com
docs_dir: docs
theme:
  name: bootstrap
  custom_dir: overrides
  static_templates:
    - sitemaps.xml
  analytics:
    gtag: G-G4V56TPB1W
  
plugins:
  - search

nav:
  - Trang chủ: index.md

